source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '2.7.2'

# A better CSV parser for ruby
gem 'smarter_csv'

# The ruby communities go-to testing tool
gem 'rspec'